### PR TITLE
Mention the Elelabs-ELU013 as well

### PR DESCRIPTION
**Pull request by walthowd**
Not sure if the 115200 SW firmware is the only compatible one for this board with the on board serial converter?

### CODE REVIEW

**Review by Adminiuga — APPROVED** [review]
Doh! it is only compatible/Tested with ELU013, i confused the two

**Comment by walthowd** [comment]
Well they are both EFR32MG13P based! Thought you were testing on a ELR023!

**Comment by Adminiuga** [comment]
The funny thing, the manufacturer attribute on my usb elelabs reports `ELR023`, even though the product page claims it to be `ELU013`
```
2020-08-18 03:09:12 INFO (MainThread) [bellows.zigbee.application] EZSP Radio manufacturer: Elelabs
2020-08-18 03:09:12 INFO (MainThread) [bellows.zigbee.application] EZSP Radio board name: ELR023
```

**Comment by Adminiuga** [comment]
Nah, was testing all of it on USB stick and went with ELR023 naming because that what was in the boarn name token.

**Comment by Adminiuga** [comment]
with pin accessibility of ELR023 I should have done all testing on it. 
How do I enable serial interface on Pi3 on gpio?

**Comment by walthowd** [comment]
No idea on the Pi; never used one!

**Comment by MattWestb** [comment]
From deCONZ [Raspbian](https://phoscon.de/en/raspbee/install#raspbian) first point is disabling the local consolle and logging so the UART can being used for other things. Allso disabling-bt or using miniuart-bt (= BT is using software UART) in the same config step so it not occupying the UART.

**Pull request merged**
